<?php

	/**
	 * Created by PhpStorm.
	 * User: user
	 * Date: 18.03.2018
	 * Time: 12:05
	 */
	class  Custom_Walker_Nav_Menu extends Walker_Nav_Menu {

		public function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
//			parent::start_el( $output, $item, $depth, $args, $id ); // TODO: Change the autogenerated stub
			$html = '';

			if ( $depth == 0 ) {

				$html .= '<li';
				if ( $args->walker->has_children ) {
					$html .= ' class="dropdown"';
				}
				$html .= '><a ';
				if ( $args->walker->has_children ) {
					$html .= ' class="dropdown-toggle" data-toggle="dropdown"';
				}

				$html .= ' href="%s">%s';
				if ( $args->walker->has_children ) {
					$html .= '<b class="caret"></b>';
				}
				$html .= '</a>';

				$output .= sprintf( $html, $item->url, strtoupper( $item->title ) );
			}
			elseif ( $depth == 1 ) {
				$output .=  '<div class="col-sm-4"><ul class="multi-column-dropdown"><h6>'.$item->title;
			}
			elseif ( $depth == 2 ) {
			 $output .='<li><a href="' .$item->url. '">'. strtoupper($item->title);

			}
//			$output .= '<li>'.$item->title.'  '.$depth;
		}


		public function end_el( &$output, $item, $depth = 0, $args = array() ) {
//			parent::end_el( $output, $item, $depth, $args ); // TODO: Change the autogenerated stub

			if ( $depth == 0 ) {
				$output .= ' </li > ';
			}
			elseif ( $depth == 1 ) {
				$output .= ' </h6></ul></div>';
			}
			elseif ( $depth == 2 ) {
				$output .= '</a></li> ';
			}

//			$output .='</li>';
		}

		public function start_lvl( &$output, $depth = 0, $args = array() ) {
//			parent::start_lvl( $output, $depth, $args ); // TODO: Change the autogenerated stub
			if ( $depth == 0 ) {

				$output .= '<ul class="dropdown-menu multi-column columns-3"><div class="row">';
			}
//			$output .='<ul>';
		}


		public function end_lvl( &$output, $depth = 0, $args = array() ) {
//			parent::end_lvl( $output, $depth, $args ); // TODO: Change the autogenerated stub
			if ( $depth == 0 ) {
				$output .= '</div></ul>';
			}
//			$output .='</ul>';

		}

	}

?>