<?php
	/**
	 * Created by PhpStorm.
	 * User: user
	 * Date: 21.03.2018
	 * Time: 8:48
	 */
	add_action( 'widgets_init', 'f_collection' );

	function f_collection() {
		register_widget( 'F_widget' );
	}

	class F_widget extends WP_Widget {

		function __construct() {
			$widget_options  = [
				'classname'   => 'fcollectionTemplate',
				'description' => 'Fcollection some description'
			];
			$control_options = [
				'width'  => 300,
				'height' => 350
			];
			parent::__construct( 'fcollection', 'Featured collection', $widget_options, $control_options );
		}

		function update( $new_instance, $old_instance ) {
//			return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
			$instance = $old_instance;
			$instance['title'] = strip_tags( $new_instance['title']);
			$instance['pcount'] = strip_tags( $new_instance['pcount']);
			return $instance;
		}

		function widget( $args, $instance ) {
//			parent::widget( $args, $instance ); // TODO: Change the autogenerated stub

			$title  = apply_filters('widget_title', $instance['title']);
				$pcount = $instance['pcount'];
			include  "fcollectionTempalte.php";
		}

		function form( $instance ) {
			$defaults = [
				'title'  => 'Featured collection',
				'pcount' => $instance['pcount']
			];

			$instance = wp_parse_args( (array) $instance, $defaults ); ?>

			<p>
				<label for="<?php echo $this->get_field_id( 'title' ) ?>">Title</label>
				<input id="<?php echo $this->get_field_id( 'title' ) ?> "
				       name="<?php echo $this->get_field_name( 'title' ) ?>"
				       value="<?php echo $instance['title'] ?>" style="width: 100%">
			</p>

			<p>
				<label for="<?php echo $this->get_field_id( 'pcount' ) ?>">Counts product</label>
				<input id="<?php echo $this->get_field_id( 'pcount' ) ?> "
				       name="<?php echo $this->get_field_name( 'pcount' ) ?>"
				       value="<?php echo $instance['pcount'] ?>" style="width: 100%">
			</p>

			<?php
		}
	}

?>